Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 184c7bb580c6e0fb2fc907760720d02aeb79ee95.

Commit 184c7bb580c6 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 184c7bb580c6 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>