ARM: imx: only call l2x0_init if it's available
This fixes a build failure with CONFIG_CACHE_L2X0=n:

	arch/arm/mach-imx/built-in.o: In function `imx3_init_l2x0':
	imx53-dt.c:(.init.text+0x190): undefined reference to `l2x0_init'
	make[2]: *** [.tmp_vmlinux1] Error 1
	make[1]: *** [sub-make] Error 2
	make: *** [all] Error 2

When the l2 cache isn't enabled the quirk introduced in
bf22c41 (MX35: Fix bogus L2 cache settings) doesn't need to be done
either.

Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>