ANDROID: input: keychord: rename waitq.task_list to waitq.head
Upstream commit bd0482d98aa0 ("sched/wait: Disambiguate
wq_entry->task_list and wq_head->task_list naming"), renamed
task_list in wait_queue_head{} and wait_queue_entry{} to head
and entry respectively to remove ambiguity, causing keychord
to run into following build error:

  CC [M]  drivers/input/misc/keychord.o
In file included from ./include/linux/kernel.h:13:0,
                 from ./include/linux/list.h:8,
                 from ./include/linux/preempt.h:10,
                 from ./include/linux/spinlock.h:50,
                 from ./include/linux/seqlock.h:35,
                 from ./include/linux/time.h:5,
                 from ./include/linux/ktime.h:24,
                 from ./include/linux/poll.h:6,
                 from drivers/input/misc/keychord.c:18:
drivers/input/misc/keychord.c: In function 'keychord_event':
drivers/input/misc/keychord.c:132:36: error: 'wait_queue_head_t' has no member named 'task_list'
    !list_empty_careful(&kdev->waitq.task_list));
                                    ^
./include/linux/printk.h:308:34: note: in definition of macro 'pr_info'
  printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
                                  ^
scripts/Makefile.build:308: recipe for target 'drivers/input/misc/keychord.o' failed
make[3]: *** [drivers/input/misc/keychord.o] Error 1

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>