arm64: xchg: Fix compilation issue with __xchg_mb
Below compilation issue is observed when compiled with clang.
Clang isn't seem to be inlining and causing the issue. Fix the issue
by forcing clang to always inline.

net/built-in.o: In function `__xchg_mb':
arch/arm64/include/asm/cmpxchg.h:99: \
                    undefined reference to `__compiletime_assert_99'
arch/arm64/include/asm/cmpxchg.h:99: \
                    undefined reference to `__compiletime_assert_99'

Change-Id: Ibcf390166826300ae5db473693a80c3d5b0475e1
Signed-off-by: Satya Durga Srinivasu Prabhala <satyap@codeaurora.org>
Signed-off-by: Prasad Sodagudi <psodagud@codeaurora.org>