Makefile: Remove -polly-run-dce from polly flags
 * clang 13 no longer supports it

fatal error: error in backend: Option -polly-run-dce not supported with NPM