docs: Do not include from kernel/rcu/srcu.c
That file went away with commit e0c439338ceb (srcu: Remove Classic SRCU)
during the 4.13 merge window, leading to errors like:

  Error: Cannot open file ./kernel/rcu/srcu.c

during the docs build.

Reported-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Jonathan Corbet <corbet@lwn.net>