xen: fix ARM build after e82727eb
The following commit:

commit e82727eb9e5052c9fe22bec9bc7056a47ae54d84
Author: Konrad Rzeszutek Wilk <konrad@kernel.org>
Date:   Fri Jul 19 11:51:31 2013 -0400

    xen: Support 64-bit PV guest receiving NMIs

breaks the Xen ARM build:

CC      drivers/xen/events.o
drivers/xen/events.c: In function 'xen_send_IPI_one':
drivers/xen/events.c:1218:6: error: 'XEN_NMI_VECTOR' undeclared (first use in this function)

Simply ifdef the undeclared symbol in the code.

Signed-off-by: Stefano Stabellini <stefano.stabellini@eu.citrix.com>