tty/amiserial: Add missing argument for tty_unlock()
commit 7e450ea394aaf50595679fd77dc46237753ec671 ("tty_lock: Localise the lock")
missed that 946b2a442d9e0797396615371f7e04e19169ed96 ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>