Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 58fe29498ff53be39b7e9aeb9e17e798c19c0cce, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer