Revert "uapi: asm-generic: ioctls: Include the termbits.h header file"
This reverts commit e9e03a2a2709d32a102e1b703dc1b4b170232cf4.

Following redefinition error is shownup, So revert this commit.
/usr/include/asm-generic/termbits.h:12:8: note: originally defined here
struct termios {
libc/usr/include/bits/termios.h:28:8: error: redefinition of ‘struct termios’

Change-Id: Ib88fb82f6b3d7514cd02fb818775eb131feec0ab
Signed-off-by: Prasad Sodagudi <psodagud@codeaurora.org>