arm: zynq: Add missing irqchip.h to common.c
The patch: "ARM: use common irqchip_init for GIC init"
(sha1: 79f91b9baafe226304e1101fd1b522b229c3da7c)
should also add linux/irqchip.h header.

Error message:
arch/arm/mach-zynq/common.c:99:14: error: 'irqchip_init'
  undeclared here (not in a function)

Signed-off-by: Michal Simek <michal.simek@xilinx.com>